### PR TITLE
[wip] build from official source tarball, cmake/ninja build chain, update meta

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

This:
- [x] updates to 8.0.3
- [x] uses the upstream released tarball rather than git
- [x] uses the newer `cmake`/`ninja` build chain
  - [x] update new dependencies
  - [ ] figure out some overlinking
- [x] updates some metadata
- [x] adds self to maintainers

### CODE REVIEW

**Comment by step21** [comment]
I would also be interested in this. What exactly is meant with 'overlinking'? (as that seems to be what is missing/wrong)

**Comment by bollwyvl** [comment]
Sorry I've let this sit! I don't recall what the over linking issue was...
It can create headaches downstream when mixed with other complex builds.
I'll see if I can warm it back up!

**Comment by step21** [comment]
No reason to be sorry. I know how it can be. Thanks for replying quickly though :)
Would be great if you could take a look again, I can also chime in once there is a build again. (would prefer not to do it locally though)

**Comment by bollwyvl** [comment]
having a look over this again... my how time flies!

the more i'm looking at it, I think it might be worth exploring a multi-output package, akin to how debian does it. so something like:

```
outputs:
  - name: swi-prolog-core
  - name: swi-prolog-nox  # no x11 deps
  - name: swi-prolog-full  # though for historical reasons, i guess this would be swi-prolog
  - name: swi-prolog-java
  - name: swi-prolog-qt
```

This would increase the chances that we could get at least _something_ it to work on windows down the road! Still haven't gotten past some build gremlins for the most recent release (8.2.1)...

**Comment by step21** [comment]
> having a look over this again... my how time flies!
> 
> the more i'm looking at it, I think it might be worth exploring a multi-output package, akin to how debian does it. so something like:
> 
> ```
> outputs:
>   - name: swi-prolog-core
>   - name: swi-prolog-nox  # no x11 deps
>   - name: swi-prolog-full  # though for historical reasons, i guess this would be swi-prolog
>   - name: swi-prolog-java
>   - name: swi-prolog-qt
> ```
> 
> This would increase the chances that we could get at least _something_ it to work on windows down the road! Still haven't gotten past some build gremlins for the most recent release (8.2.1)...

multi output is definitely possible on conda-forge, and not that complicated.

**Comment by step21** [comment]
I am experimenting with my own PR for now.
So far -
* would def use tarball, not github, means much less work. This means sticking with 'stable' releases probably, as at least for 7.7 there is not tarbal and while it is tagged on github, it is not in the list of official/stable releases.
* since 8.x or even end of 7.7 they use cmake, so have to switch to that.

**Comment by bollwyvl** [comment]
Thanks for looking!

Right, I think using the official stable tarball is the right way, as it
handles all the submodules:

https://www.swi-prolog.org/download/stable

Getting dev releases can be a follow-on, long running branch... They seem
quite disciplined, and folk may want it, but I don't foresee a lot of
downstreams requiring it.

Ninja and cmake for sure. The last thing I stalled on was the openssl
tests. Keeping the tests is very important to me, from a maintenance
perspective, and it seems like openssl should probably be a hard
requirement.

On downstreams: I'm _actually_ interested in the first place for packaging
terminusdb, which also has a swipl-installed package (and a gnarly rust
toolchain). I'm very interested in how we can package those, too, as I
really dislike stuff that pops off to the internet the first time you use
it. So much to learn!

**Comment by step21** [comment]
Thanks for the info. Also agree that openssl should be a hard requirement.
But what do you mean by Openssl tests? ssl tests for swipl?

**Comment by bollwyvl** [comment]
Right, in this pr, build.sh runs the tests with ctest after a successful
build. From a ci perspective, this helps save a test environment solve if
something's really broken, and helps keep us honest.

I think with the cmake component build, it may be possible to (separately)
package the tests, and run them in the "real" environment, plus ctest, and
would probably be worth it... Probably nobody would ever install said
package, but again, I don't know what I don't know about prolog!

**Comment by step21** [comment]
Mmh. I think the conda-forge strategy, especially with regard to things that can be executed/are not libraries is just to often also allow something like `swipl -h` or for python modules  `import <module>` as most major errors you will catch right away, and where testing would be important, it is also really difficult and I just rely on upstream doing those tests before release. (one example being web3.py, which test against all kinds of clients and network configs, which I could never run on conda-forge)
Running a built-in testsuite if of course also great, but in cases where some tests of 9000 tests broke the build I also know they were skipped, especially if sometimes even upstream does not know why. So if f.e. openssl tests cannot be run because of CI limitations, for me this wouldn't be a blocker.

**Comment by bollwyvl** [comment]
Good point! There are some differences in opinion and practice from
different maintainer communities. Pure python packages with simple
dependencies, some of which don't ship tests in their distributions, often
slide. Once complex binary dependencies or build steps crop up... Well...

Selfishly, I've found when bootstrapping a whole language/interpreter
ecosystem from source, it pays to do the most testing possible... As a
maintainer, I'd rather have a Lang X, vN+1 pr languish for a while getting
the tests to pass vs blindly shipping and waiting for users to debug it for
us.

**Pull request merged**
