### PR TITLE
Update version to 9.1.3

### PR DESCRIPTION
**Pull request by mossbanay**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [X] Ensured the license file is being packaged.

Hi, I'm looking at updating this package to include a more recent version of swi-prolog. The current version looks to be ~4 years old.

The instructions for re-render seem not to apply to the changes I've made, let me know if I've misunderstood this please!

It looks like the license is unchanged in 9.1.3.

### CODE REVIEW

**Comment by Guthur** [comment]
@conda-forge-admin circleci is failing at the checkout_merge_commit.sh script.

**Comment by Guthur** [comment]
> @conda-forge-admin circleci is failing at the checkout_merge_commit.sh script.

@conda-forge/core circlci integration issue, have there been upstream changes

**Comment by mossbanay** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
@mossbanay apparently we just landed #6, which got us up to 9.0.4... if this is still important to you, please consider updating this PR, and ideally, add yourself as a maintainer in `extra`.

**Comment by Guthur** [comment]
@bollwyvl @mossbanay is my colleague. We will be ok with 9.0.4 :)

**Pull request closed without merging**
