### PR TITLE
Bump version 9 0 4

### PR DESCRIPTION
**Pull request by Guthur**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Guthur** [comment]
@conda/conda-core this feedstock seems to be orphaned, can you help merge this PR.

Thanks.

**Comment by Guthur** [comment]
@conda-forge-admin the maintainer may be unreachable for this feedstock, can you help merge?

Thanks.

**Comment by Guthur** [comment]
@conda-forge/core I am quite confident this repository has become orphaned from it's maintainer due the lack of activity from them on any of the recent PRs. Can you help merge this PR?
Thanks.

Additionally I'm willing to volunteer as an additional maintainer.

**Comment by hmaarrfk** [comment]
Thank you!

**Comment by bollwyvl** [comment]
Huh, guess I am signed up for this now? I mean... ok, but my need sorta moved on from here, but do recognize it's important.

@Guthur as you've poked the bear, please consider also adding yourself with a [bot command issue](https://github.com/conda-forge/swi-prolog-feedstock/issues/new?assignees=&labels=&template=2-bot-commands.yml).

**Comment by hmaarrfk** [comment]
sorry opps, i thoguth they added themselves . i got mixed up in the github handles.

**Pull request merged**
